### ISSUE TITLE
2019 Roadmap

### ISSUE THREAD

**Issue by theo-bech** [theo-bech/Young-Accessibility-Leaders#1]
**_Let's create an open curriculum on assistive technology for middle and high school students!_**

This issue is the roadmap for Young Accessibility Leaders. Here, you can review the tasks that need to be completed to reach our current Milestones. 

Project-driven tech classes in secondary education (IT, robotics, etc.) could have a much greater influence on students if they covered the ways in which technology can be used for positive community engagement. A curriculum on assistive technology - any tools used by people with disabilities - could familiarize students with disability and accessibility, offer an example of the work engineers and developers do to assist people with disabilities, and inspire them to effect change in their communities as future professionals. 

Young Accessibility Leaders aims to do just that: create a hands-on curriculum on assistive technology as well as a platform where educators can access the materials and collaborate with developers, disability professionals, and people with disabilities to evaluate and contribute to the resources available. 

The following roadmap lists the Milestones and corresponding tasks **as of 4/25/2019**.

## Milestone: Complete Introductory Course

> The introductory course gives students a taste of what's ahead, familiarizing them with the concepts of disability,  accessibility, and assistive technology, as well some of the challenges in the field.

- [x] Compile teacher's guide.
- [x] Translate introductory course into English.

## Milestone: Complete Project 1 Study & Teaching Materials

> Project 1 is a basic mouse stabilizer script concept for people with [Essential Tremor](https://en.wikipedia.org/wiki/Essential_tremor) using AutoHotKey.

- [ ] Complete presentation.
- [ ] Compile teacher's guide. 
- [x] Check code.

## Milestone: Complete Project 2 Study & Teaching Materials

> Project 2 is a smart doorbell for people with [hearing](https://www.disabled-world.com/disability/types/hearing/) and/or [mobility](https://www.disabled-world.com/disability/types/mobility/) impairments, built using a RaspberryPi and Python code. It's already been taught in a robotics class at the Model Experiment Junior High School of the University of Macedonia, so most of the resources are complete!

- [ ] Complete presentation.
- [ ] Compile teacher's guide. 
- [ ] Check code.
- [x] Translate materials to English.

## Milestone: Create GitHub Repository

> The goal of Young Accessibility Leaders is to build a platform where educators and other contributors (especially people with disabilities) will be able to access the project materials and share ideas and resources. Creating a GitHub repository is a good place to start for contributors with technical backgrounds. 

- [x] Create a GitHub repository.
- [x] Add readme.
- [x] Add license.
- [x] Add contributor guidelines.
- [x] Add code of conduct.

## Milestone: Build Website

> For contributors with non-technical backgrounds and to avoid the hassle of GitHub, we need to build a website where the resources will be more easily accessible.

- [ ] Design website.
- [x] Add readme, contributor guidelines, code of conduct, and FAQ.
- [ ] Double-check for accessibility!

## Milestone: 4th EKEDISY Conference 

> The curriculum will be presented in the [4th EKEDISY Conference](http://ekedisyconference.weebly.com/) between May 10-12th in Athens. The presentation will be part of a workshop on planning project-driven lessons in assistive technology.

- [x] Create teacher's guide on designing projects.
- [x] Create teacher's guide on contacting disability organizations/hosting speakers with disabilities. 
- [x] Prepare workshop/conference materials.

## Milestone: Compile Wiki
> It'll be nice to have all teaching materials in wiki format. 

- [x] Create a wiki.
- [x] Curate and adjust materials.
- [x] Check for accessibility (alt-text, visuals).

## Milestone: Expand Curriculum/Enhance Availability

> The curriculum needs more projects, and all existing resources need to be translated into other languages to increase reach/impact.

- [ ] Add alt-text to existing materials.
- [ ] Translate existing materials into French. 
- [ ] Translate existing materials into Spanish.
- [ ] Translate existing materials into German.
- [ ] Create Project 3.

**Comment by bastianhell** [comment]
Nice job Theo!, I like the way you choose to build the roadmap. Are these Milestones either order by priority or chronological order? Any other?

**Comment by theo-bech** [comment]
> 
> 
> Nice job Theo!, I like the way you choose to build the roadmap. Are these Milestones either order by priority or chronological order? Any other?

@bastianhell thanks! They are in chronological order, but not entirely - some tasks can only be completed serially, but some milestones don't depend on the completion of the ones listed before them. Take "Create GitHub Repository" for instance.
